# conf/config.yaml
random_seed: 42

learning_rate: 0.001           # 초기 기본 학습률 (클라이언트에서 후보와 비교)
model_type: 'Pytorch'          # 유지 필수 값
model:
  _target_: models.MNISTClassifier
  output_size: 10

dataset:
  name: 'MNIST'
  validation_split: 0.2

# 후보 하이퍼파라미터 (학습률 후보) – Genetic CFL 초기값
hyperparams: [0.001, 0.005, 0.01]

# client
task_id: 'test1'
wandb: 
  use: true
  key: '38f6cf3c2c37660d42ebfe8ab434b72d34be3b31'
  account: 'rirakang@gachon.ac.kr'
  project: '${dataset.name}_${task_id}'

# server
num_epochs: 1
batch_size: 128
num_rounds: 2
clients_per_round: 1

server:
  strategy:
    _target_: flwr.server.strategy.FedAvg
    fraction_fit: 0.00001
    fraction_evaluate: 0.000001
    min_fit_clients: ${clients_per_round}
    min_available_clients: ${clients_per_round}
    min_evaluate_clients: ${clients_per_round}
